enableScripts: true

nodeLinker: node-modules

packageExtensions:
  eslint-plugin-react-compiler@*:
    peerDependenciesMeta:
      eslint:
        optional: true

yarnPath: .yarn/releases/yarn-4.12.0.cjs
