nodeLinker: hoisted

allowedDeprecatedVersions:
  "@babel/plugin-proposal-private-methods": 7.18.6
  uuid: 7.0.3

allowBuilds:
  "@firebase/util": true
  "@shopify/react-native-skia": true
  msgpackr-extract: true
  protobufjs: true

packageExtensions:
  eslint-plugin-react-compiler@*:
    peerDependenciesMeta:
      eslint:
        optional: true

minimumReleaseAgeExclude:
  - "@typescript/native-preview-darwin-arm64@7.0.0-dev.20260705.1"
  - "@typescript/native-preview-darwin-x64@7.0.0-dev.20260705.1"
  - "@typescript/native-preview-linux-arm64@7.0.0-dev.20260705.1"
  - "@typescript/native-preview-linux-arm@7.0.0-dev.20260705.1"
  - "@typescript/native-preview-linux-x64@7.0.0-dev.20260705.1"
  - "@typescript/native-preview-win32-arm64@7.0.0-dev.20260705.1"
  - "@typescript/native-preview-win32-x64@7.0.0-dev.20260705.1"
  - "@typescript/native-preview@7.0.0-dev.20260705.1"
