// Reexport the native module. On web, it will be resolved to IosBatchAssetsInfoModule.web.ts
// and on native platforms to IosBatchAssetsInfoModule.ts
// Note: Native module only available on iOS. Use isBatchAssetInfoAvailable() to check before calling.
export {
  allowsAutomaticDeepScanFollowup,
  beginAssetScan,
  beginDatabaseBackedIncrementalAssetScan,
  beginIncrementalAssetScan,
  clearPhotoAssetThumbnailCache,
  DEFAULT_VISIT_FOOD_DETECTION_STRATEGY,
  detectFoodInImageBatch,
  endAssetScan,
  endPhotoAssetThumbnailPreheat,
  getAssetInfoBatch,
  getAssetScanPage,
  getResolvedPhotoScanStrategy,
  getResolvedPhotoAssetThumbnailPreheatStrategy,
  getResolvedVisitFoodDetectionStrategy,
  getResolvedVisionPageOrchestrationStrategy,
  getResolvedVisionResultTransport,
  getVisionResultPageSize,
  isAssetScanAvailable,
  isBatchAssetInfoAvailable,
  isDatabaseBackedIncrementalAssetScanAvailable,
  isIncrementalAssetScanAvailable,
  isPhotoAssetThumbnailAvailable,
  isPhotoAssetThumbnailPreheatAvailable,
  isVisionVisitFoodValidationModeEnabled,
  FULL_PLAN_VISIT_FOOD_DETECTION_STRATEGY,
  RANK3_BULK_TAIL_VISIT_FOOD_DETECTION_STRATEGY,
  resolveVisitFoodDetectionStrategy,
  updatePhotoAssetThumbnailPreheat,
  DISABLED_PHOTO_ASSET_THUMBNAIL_PREHEAT_STRATEGY,
  WINDOWED_PHOTO_ASSET_THUMBNAIL_PREHEAT_STRATEGY,
  type AssetScanPage,
  type AssetScanPageOptions,
  type AssetScanRecord,
  type AssetScanSession,
  type BatchAssetInfo,
  type FoodDetectionOptions,
  type FoodDetectionResult,
  type IncrementalAssetScanSession,
  type PhotoScanStrategy,
  type PhotoAssetThumbnailPixelTarget,
  type PhotoAssetThumbnailPreheatStrategy,
  type VisitFoodDetectionStrategy,
  type VisionPageOrchestrationStrategy,
  type VisionResultTransport,
} from "./src/index";

export {
  PhotoAssetThumbnail,
  type PhotoAssetThumbnailErrorEvent,
  type PhotoAssetThumbnailLoadEvent,
  type PhotoAssetThumbnailProps,
} from "./src/PhotoAssetThumbnail";
